before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"

before_script:
  - bundle update

notifications:
  email: false

bundler_args: --without test --jobs 3 --retry 3

language: ruby
rvm:
 - 2.0.0

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec