before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"

before_script:
  - bundle update

notifications:
  email: false

language: ruby
rvm:
 - 2.0.0
 - rbx
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec